<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="forXML.css"?>
<!DOCTYPE students [
<!ELEMENT students (example, student)>
<!ELEMENT example (euniversity, ename, esurname, eage)>
<!ELEMENT student (university, name, surname, age)>
<!ELEMENT euniversity (#PCDATA)>
<!ELEMENT ename (#PCDATA)>
<!ELEMENT esurname (#PCDATA)>
<!ELEMENT eage (#PCDATA)>
<!ELEMENT university (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ENTITY enamed "~">
]>
<students>
    <example>
        <euniversity>&enamed;Университет&enamed;</euniversity>
        <ename>&enamed;Имя&enamed;</ename>
        <esurname>&enamed;Фамилия&enamed;</esurname>
        <eage>&enamed;Возраст&enamed;</eage>
    </example>
    <student>
        <university>БГТУ</university>
        <name>Виолетта</name>
        <surname>Бабич</surname>
        <age>17</age>
    </student>
    <student>
        <university>БГУФК</university>
        <name>Виктория</name>
        <surname>Угоренко</surname>
        <age>45</age></student>
    <student>
        <university>БГУИР</university>
        <name>Оля</name>
        <surname>Лускина</surname>
        <age>18</age></student>
</students>